import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import CountriesCount from "../components/CountriesCount";
import { supabaseClient } from "../config/supabaseClient";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  const { countriesList } = props;
  const [countriesListData, setCountriesListData] = useState(countriesList);

  const handleDelete = async (indexToDelete) => {
    const { error } = await supabaseClient
      .from("countries")
      .delete()
      .eq("id", indexToDelete);
    if (!error) {
      console.log("Delete success");

      const { data: countriesData, error: countriesDataFetchingError } =
        await supabaseClient.from("countries").select("*");
      if (!countriesDataFetchingError) {
        setCountriesListData(countriesData);
      }
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.tableContainer}>
          <table>
            <thead>
              <tr>
                <th>country_name</th>
                <th>country_iso2</th>
                <th>country_iso3</th>
                <th>country_local_name</th>
                <th>country_continent</th>
              </tr>
            </thead>
            <tbody>
              {countriesListData.map((country, index) => {
                return (
                  <tr key={country.id}>
                    <td>{country.name}</td>
                    <td>{country.iso2}</td>
                    <td>{country.iso3}</td>
                    <td>{country.local_name}</td>
                    <td>{country.continent}</td>
                    <td>
                      <button
                        title="delete"
                        onClick={() => handleDelete(country.id)}
                      >
                        delete
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
            <tfoot></tfoot>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <CountriesCount />
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  console.log("inside get static props");
  const { data: countriesList, error } = await supabaseClient
    .from("countries")
    .select("*", { count: "exact" });
  console.log(countriesList);

  if (error || countriesList.length < 1) {
    console.log("Check data in supabase");
    return;
  }
  return {
    props: {
      countriesList,
    },
  };
}
